debug: true

build:
  image: rails:onbuild
  environment:
    - RAILS_ENV=test
  commands:
    - bundle install --path tmp/bundle
    - until pg_isready -h localhost -U postgres -q; do sleep 1; done
    - rake db:test:prepare
    - rake test

compose:
  postgres:
    image: postgres

publish:
  docker:
    email: $$DOCKER_EMAIL
    username: $$DOCKER_USER
    password: $$DOCKER_PASSWORD
    insecure: false
    repo: $$DOCKER_USER/in-spiritus
    tag:
      - $$COMMIT
      - latest
    when:
      branch: master
    load: docker/image.tar
    save:
      destination: docker/image.tar
      tag: $$COMMIT

cache:
  mount:
    - docker/image.tar
    - tmp/bundle
