sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
services:
- postgresql
- redis
script:
- rake db:test:prepare
- rake
deploy:
  provider: cloud66
  redeployment_hook: ${CLOUD66_REDEPLOYMENT_HOOK}
  on:
    branch: development
    repo: mlvk/in-spiritus
addons:
  hosts:
    - db
