language: ruby
sudo: required

services:
  - postgresql
  - docker

before_script:
  - RAILS_ENV=test

install:
  - bundle install --without development --deployment --jobs=3 --retry=3

script:
  - bundle exec rake db:setup
  - rake test

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build in-spiritus .
  - docker tag in-spiritus "$DOCKER_USERNAME"/in-spiritus:$TRAVIS_COMMIT
  - docker tag in-spiritus "$DOCKER_USERNAME"/in-spiritus
  - docker push "$DOCKER_USERNAME"/in-spiritus
