sudo: false
language: ruby
cache: bundler
rvm:
- 2.3.1
services:
- postgresql
- redis
script:
- rake db:test:prepare
- rake
deploy:
  provider: cloud66
  redeployment_hook:
    secure: "Z3tq386kgawOeVvhZOZofyynwyMsa+DHjAxeURn21FzuMd3u9x8hLrv1kMUngCljMxJkMNG5rMKtKZfTq5LpeFUUdUq780tnPudjcp+Kihcaw1RcF3NfEtA3O+xPpsnHMz8/4BmHFY/rKApNkgpSJNe/BZ9GnyeGfo2tFfn6rpw47nhsrRJM/z8G33LUiei5RIJoBqKmc93nmMSd5zOM1s/iKC6ufrgW7iyGXVj2EXlHhQcRD5GAYvKlvF+VCuBCqk1pWTITr6RhrZGQVH8wJCU6AGpCoWXTpCrH1GkG2cqvZvz08nLs+5CuypIlrgTw0GPb++98s4TOQLPjHzoQkePlZVd7EVQrhfS6VBJETtusYFWAQ6Jqxq1LliD9BB3bt7LDx+qkIwylhcvToVoQo1wzGWK+6BnXGQf+aiwmulgOGFVXIbcJxUxNDymd803Bp46GX3IzKNLyiYEZnguBcCQAynHHjPNmT9eSo+j/D5meBS44BSuCmrEqp2vp6k2+Qt0lkimrLIb9bdCbVlVonEjvSbClYWIem4UNtbxeklklgWxkMoff8drgl8A8i0xiNBXfcCUxIWCdwSHVcWeZl7ZCUhwix2eEdsNaz7aaiVsH9KKdxbt/kkWlQWFRXLoHXXKlL/f/QK42N+fzm09SeAk33oxxMzYlc7yRZAOapb4="
  on:
    repo: mlvk/in-spiritus
