language: ruby

rvm:
  - 2.3.0

sudo: false
cache: bundler

env:
  - RAILS_ENV=test

before_install: "rm ${BUNDLE_GEMFILE}.lock"

before_script: "bundle update"

script:
  - bundle exec rake db:setup
  - bundle exec rake test

after_success:
  - sudo docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - sudo docker build in-spiritus .
  - sudo docker tag in-spiritus "$DOCKER_USERNAME"/in-spiritus:$TRAVIS_COMMIT
  - sudo docker tag in-spiritus "$DOCKER_USERNAME"/in-spiritus
  - sudo docker push "$DOCKER_USERNAME"/in-spiritus

services:
  - postgresql
  - docker
