default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: in_spiritus_development

test:
  <<: *default
  database: in_spiritus_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  username: <%= ENV["DATABASE_USER_NAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
